spring:
  jpa:
    show-sql: true
    properties:
      hiberanate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://192.168.2.2:5432/traffic_unit
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres