spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/jpa_test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8